#ifndef __MonitorAbout__
#define __MonitorAbout__

/**
@file
Subclass of AboutDialog, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

//// end generated include

/** Implementing AboutDialog */
class MonitorAbout : public AboutDialog
{
	protected:
		// Handlers for AboutDialog events.
		void OnClick( wxCommandEvent& event );
	public:
		/** Constructor */
		MonitorAbout( wxWindow* parent );
	//// end generated class members



};

#endif // __MonitorAbout__
