#ifndef __IdBurnerAboutDialog__
#define __IdBurnerAboutDialog__

/**
@file
Subclass of AboutDialog, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

//// end generated include

/** Implementing AboutDialog */
class IdBurnerAboutDialog : public AboutDialog
{
	protected:
		// Handlers for AboutDialog events.
		void OnClick( wxCommandEvent& event );
	public:
		/** Constructor */
		IdBurnerAboutDialog( wxWindow* parent );
	//// end generated class members

};

#endif // __IdBurnerAboutDialog__
