#ifndef __IdBurnerEditDialog__
#define __IdBurnerEditDialog__

/**
@file
Subclass of EditDialog, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"
#include "IdBurnerApp.h"


//// end generated include

/** Implementing EditDialog */
class IdBurnerEditDialog : public EditDialog
{
    private:
        ConfigReader configuration;
        wxTextValidator idValidator;
        std::string old_name;
        std::string section;
        std::string &new_name;
        bool advanced;
	protected:
		// Handlers for EditDialog events.
		void checkCounter( wxCommandEvent& event);
		void onSave( wxCommandEvent& event );
		void onCancel( wxCommandEvent& event );
	public:
		/** Constructor */
		IdBurnerEditDialog( wxWindow* parent , std::string file_path, std::string device_type, std::string &name_device);
	//// end generated class members

};

#endif // __IdBurnerEditDialog__
