#ifndef __IdBurnerMain__
#define __IdBurnerMain__

/**
@file
Subclass of GUIFrame, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

//// end generated include

#include <DigiProtocol.h>
#include <vector>

#include "IdBurnerAboutDialog.h"
#include "IdBurnerEditDialog.h"
#include "IdBurnerAddDialog.h"
#include "ConfigReader.h"


/** Implementing GUIFrame */
class IdBurnerMain : public GUIFrame
{
	protected:
		// Handlers for GUIFrame events.
		void OnClose( wxCloseEvent& event );
		void OnQuit( wxCommandEvent& event );
		void OnAbout( wxCommandEvent& event );
		void OnRefresh( wxCommandEvent& event );
		void OnReload( wxCommandEvent& event);
		void OnTypeChoice( wxCommandEvent& event);
		void OnAdd( wxCommandEvent& event );
		void OnEdit( wxCommandEvent& event );
		void OnDelete( wxCommandEvent& event );
		void OnDateUpdate( wxDateEvent& event );
		void UsingSystemDate( wxCommandEvent& event );
		void OnManualCode( wxCommandEvent& event );
		void OnBurn( wxCommandEvent& event );
	public:
		/** Constructor */
		IdBurnerMain( wxWindow* parent );
	//// end generated class members
	private:
        void RefreshDeviceList(std::string selection="");
        void ReloadConfig(std::string selection="");
        void UpdateID(std::string selection);
        std::string wrapID(std::string counter);

        bool manual;

        ConfigReader configuration;
        wxTextValidator idValidator;
        wxTextValidator numValidator;
        std::vector<std::string> IDlist;

};

#endif // __IdBurnerMain__
